from . import base
from . import product_category
from . import product_attribute_company
from . import product_tag_company
from . import partner_category
from . import partner_industry
from . import res_bank
from . import res_partner_bank
from . import stock_warehouse
from . import stock_picking_type
from . import pos_config
from . import pos_category
from . import pos_note
