{
    "name": "report_sale_order_accumulate",
    "summary": """Informe de ventas acumulados por tipo de producto""",
    "version": "14.0.1.0.0",
    "description": """Informe de ventas acumulados por tipo de producto""",
    "author": "DDL,Camilo",
    "company": "Xtendoo",
    "website": "https://xtendoo.es",
    "category": "Extra Tools",
    "depends": ["base", "account", "sale", "web", "stock",],
    "license": "AGPL-3",
    "depends": ["stock",],
    "data": ["reports/report_saleorder_accumulate.xml",],
    "installable": True,
    "auto_install": False,
}
