{
    "name": "Customer Invoice and Delivery Address",
    "author": "Ascetic Business Solution",
    "category": "Sales",
    "summary": """Customer Invoice and Delivery address""",
    "license": "AGPL-3",
    "website": "http://www.asceticbs.com",
    "version": "13.0.1.0",
    "depends": ["sale_management"],
    "data": [],
    "images": ["static/description/banner.png"],
    "installable": True,
    "application": True,
    "auto_install": False,
}
