{
    'name': 'Xtendoo Custom Product Labels',
    'version': '18.0.1.0.1',
    'category': 'Extra Tools',
    'author': 'Abraham Carrasco (Xtendoo)',
    'website': '',
    'license': 'LGPL-3',
    'summary': 'Print custom product labels',
    'images': [],
    'depends': [
        'product',
        'stock',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/product_data.xml',
        'data/print_label_type_data.xml',
        'data/ir_filters_data.xml',
        'report/product_label_reports.xml',
        'report/product_label_templates.xml',
        'wizard/print_product_label_views.xml',
        'views/res_config_settings_views.xml',
        'views/stock_picking_views.xml',
    ],
    'demo': [
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}
