{
    "name": "Document Format GREGO",
    "summary": """Formatos de documentos entregados por Xtendoo""",
    "version": "15.0.1.0.0",
    "description": """Formatos de documentos entregados por Xtendoo""",
    "author": "Daniel Dominguez",
    "company": "Xtendoo",
    "website": "http://xtendoo.es",
    "category": "Extra Tools",
    "depends": ["base", "account", "sale", "web", "stock", "product",],
    "license": "AGPL-3",
    "depends": [
        "sale",
        "stock",
        "stock_picking_report_valued",
        "product",
        "account",
        "account_invoice_report_due_list",
        "account_payment_partner",
        "account_invoice_report_grouped_by_picking",
        "mail",
        "contacts",
    ],
    "data": [
        "data/paper_format_label.xml",
        "views/stock_picking/stock_picking_view.xml",
        "views/delivery/report_delivery.xml",
        "views/delivery/delivery_document.xml",
        "views/delivery/delivery_commodity.xml",
        "views/delivery/delivery_document_without_price.xml",
        "views/delivery/delivery_pallet_label.xml",
        "views/invoice/invoice_document.xml",
        "views/invoice/invoice_dossier.xml",
        "views/invoice/invoice_gruped_by_picking.xml",
        "views/layout/external_layout_clean.xml",
        "views/sale/sale_order_document.xml",
        "views/sale/sale_order_blank_document.xml",
        "views/label/product_label.xml",
        #"report/report_label_barcode.xml",
        #"report/report_label_barcode_template.xml",
        "views/email_default_template/account_invoice_send_views.xml",
        "views/purchase/purchase.xml",
    ],
    "installable": True,
    "auto_install": False,
}
