{
    "name": "Document Format Clean",
    "summary": """Formatos de documentos entregados por Xtendoo""",
    "version": "16.0.1.0.0",
    "description": """Formatos de documentos entregados por Xtendoo""",
    "author": "Manuel Calero, Daniel Dominguez",
    "company": "Xtendoo",
    "website": "http://xtendoo.es",
    "category": "Extra Tools",
    "license": "AGPL-3",
    "depends": [
        "web",
        "base",
        "purchase",
        "sale",
        "stock",
        "stock_picking_report_valued",
        "product",
        "account",
        "account_invoice_report_due_list",
        "account_payment_partner",
        "mail",
        "contacts",
        "l10n_es",
        "l10n_es_partner",
    ],
    "data": [
        "views/stock_picking/stock_picking_view.xml",
        "views/delivery/delivery_document.xml",
        "views/delivery/delivery_commodity.xml",
        #"views/delivery/delivery_document_original_number.xml",
        "views/invoice/invoice_document.xml",
        "views/invoice/invoice_dossier.xml",
        #"views/invoice/invoice_gruped_by_picking.xml",
        "views/layout/external_layout_clean.xml",
        "views/sale/sale_order_document.xml",
        "views/sale/sale_order_blank_document.xml",
        "views/purchase/purchase.xml",
        "views/invoice/account_tax_template.xml",
    ],
    "installable": True,
    "auto_install": False,
}
