{
    "name": "POS Conventional (No táctil)",
    "version": "19.0.1.0.0",
    "category": "Point of Sale",
    "summary": "Modo de punto de venta optimizado para equipos sin pantalla táctil",
    "description": "Modo de punto de venta optimizado para equipos sin pantalla táctil",
    "author": "Guillermo Bárcena López",
    "website": "https://www.xtendoo.es",
    "license": "AGPL-3",
    "depends": [
        "point_of_sale",
        "sale",
        "mail",
    ],
    "data": [
        "data/pos_session_sequence.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/pos_config_kanban_views.xml",
        "views/pos_config_views.xml",
        "views/pos_session_opening_wizard_views.xml",
        "views/pos_session_pin_wizard_views.xml",
        "views/pos_session_closing_wizard_views.xml",
        "views/pos_session_cash_move_wizard_views.xml",
        "views/pos_cash_calculator_wizard_views.xml",
        "views/pos_order_views.xml",
        "views/pos_payment_views.xml",
        "views/report_receipt.xml",
        "views/report_sale_details_customer_account.xml",
        "views/albaran_receipt.xml",
        "data/mail_template_pos_receipt.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "pos_conventional/static/src/css/pos_conventional_wizards.css",
            "pos_conventional/static/src/js/pos_order_list_controller.js",
            "pos_conventional/static/src/js/pos_order_form_barcode_controller.js",
            "pos_conventional/static/src/js/pos_print_iframe.js",
            "pos_conventional/static/src/js/pos_print_client_action.js",
            "pos_conventional/static/src/js/pos_new_order_action.js",
            "pos_conventional/static/src/js/pos_order_list_auto_open.js",
            "pos_conventional/static/src/xml/pos_order_list_view.xml",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
