{
    "name": "POS Conventional (No táctil)",
    "version": "19.0.1.0.0",
    "category": "Point of Sale",
    "summary": "Modo de punto de venta optimizado para equipos sin pantalla táctil",
    "description": """
        Añade una opción en la configuración del Punto de Venta para activar
        un modo optimizado para equipos sin pantalla táctil.
    """,
    "author": "Guillermo Bárcena López",
    "website": "https://www.xtendoo.es",
    "license": "AGPL-3",
    "depends": [
        "point_of_sale",
        "sale",
        "mail",
        "xtendoo_pos_receipt",
    ],
    "data": [
        "data/pos_session_sequence.xml",
        "security/ir.model.access.csv",
        "security/pos_config_record_rules.xml",
        "views/res_users_views.xml",
        "views/res_config_settings_views.xml",
        "views/pos_config_kanban_views.xml",
        "views/pos_config_views.xml",
        "views/pos_session_opening_wizard_views.xml",
        "views/pos_session_pin_wizard_views.xml",
        "views/pos_session_closing_wizard_views.xml",
        "views/pos_session_cash_move_wizard_views.xml",
        "views/pos_cash_calculator_wizard_views.xml",
        "views/pos_make_payment_wizard_views.xml",
        "views/pos_payment_views.xml",
        "views/pos_order_views.xml",

        "views/report_receipt.xml",
        "views/report_sale_details_customer_account.xml",
        "views/albaran_receipt.xml",
        "data/mail_template_pos_receipt.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "pos_conventional/static/src/css/cashbox.css",
            "pos_conventional/static/src/scss/pos_conventional_wizard.scss",
            # "pos_conventional/static/src/css/pos_session_closing.css",
            "pos_conventional/static/src/js/pos_order_list_controller.js",
            "pos_conventional/static/src/js/pos_order_form_barcode_controller.js",
            "pos_conventional/static/src/js/pos_print_iframe.js",
            "pos_conventional/static/src/js/pos_print_client_action.js",
            "pos_conventional/static/src/js/pos_receipt_client_action.js",
            "pos_conventional/static/src/js/pos_new_order_action.js",
            "pos_conventional/static/src/js/pos_order_list_auto_open.js",
            "pos_conventional/static/src/js/opening_popup.js",
            "pos_conventional/static/src/js/closing_popup.js",
            "pos_conventional/static/src/js/cash_move_popup.js",
            "pos_conventional/static/src/xml/pos_order_list_view.xml",
            "pos_conventional/static/src/xml/opening_popup.xml",
            "pos_conventional/static/src/xml/closing_popup.xml",
            "pos_conventional/static/src/xml/cash_move_popup.xml",
            "pos_conventional/static/src/js/payment_popup.js",
            "pos_conventional/static/src/js/pos_payment_buttons.js",
            "pos_conventional/static/src/xml/payment_popup.xml",
            "pos_conventional/static/src/xml/pos_payment_buttons.xml",
            # Include original POS receipt assets for native printing
            "point_of_sale/static/lib/qrcode.js",
            "point_of_sale/static/src/utils.js",
            "point_of_sale/static/src/css/pos_receipts.css",
            "xtendoo_pos_receipt/static/src/css/pos_receipt.scss",
            "point_of_sale/static/src/app/utils/use_timed_press.js",
            "point_of_sale/static/src/app/components/centered_icon/centered_icon.js",
            "point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.js",
            "point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml",
            "point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.xml",
            "point_of_sale/static/src/app/store/order_change_receipt_template.xml",
            "point_of_sale/static/src/app/components/orderline/orderline.js",
            "point_of_sale/static/src/app/components/orderline/orderline.xml",
            "point_of_sale/static/src/app/screens/receipt_screen/receipt/receipt_header/receipt_header.js",
            "point_of_sale/static/src/app/screens/receipt_screen/receipt/receipt_header/receipt_header.xml",
            "point_of_sale/static/src/app/components/order_display/order_display.js",
            "point_of_sale/static/src/app/components/order_display/order_display.xml",
            "xtendoo_pos_receipt/static/src/xml/receipt_templates.xml",
            "point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
