# Copyright 2026 Xtendoo - Manuel Calero
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl).

import logging

from odoo import models

_logger = logging.getLogger(__name__)


class AccountMove(models.Model):
    _inherit = "account.move"

    def write(self, vals):
        """Override write to detect when invoices are reset to draft and clear cached PDFs."""
        # Detect moves being reset to draft from posted/cancel state
        moves_to_clear_cache = self.env['account.move']

        if 'state' in vals and vals['state'] == 'draft':
            # Filter only invoice types that should have their PDFs cleared
            invoice_types = ('out_invoice', 'out_refund', 'in_invoice', 'in_refund')
            moves_to_clear_cache = self.filtered(
                lambda m: m.state in ('posted', 'cancel')
                and m.move_type in invoice_types
            )

        # Call super to perform the state change
        result = super().write(vals)

        # After successful state change, clear cached PDFs
        if moves_to_clear_cache:
            moves_to_clear_cache._xtd_unlink_cached_invoice_pdfs()

        return result

    def _xtd_unlink_cached_invoice_pdfs(self):
        """
        Delete system-generated PDF attachments for invoice reports.

        This method removes only the cached PDF files generated by Odoo's
        standard invoice report, preserving any user-uploaded attachments.
        It's called automatically when an invoice is reset to draft.
        """
        if not self:
            return

        # Search for PDF attachments linked to these invoices
        attachments = self.env['ir.attachment'].sudo().search([
            ('res_model', '=', 'account.move'),
            ('res_id', 'in', self.ids),
            ('mimetype', '=', 'application/pdf'),
        ])

        if not attachments:
            return

        # Filter to delete only system-generated invoice report PDFs
        attachments_to_delete = self.env['ir.attachment']

        for move in self:
            # Get the expected report name for this invoice
            # In Odoo 17, the standard invoice report generates PDFs with names like:
            # "INV/2024/00001.pdf" or similar based on the invoice number
            expected_names = self._xtd_get_expected_pdf_names(move)

            # Find attachments matching expected names
            move_attachments = attachments.filtered(
                lambda a: a.res_id == move.id and a.name in expected_names
            )

            if move_attachments:
                _logger.info(
                    "Clearing %d cached invoice PDF(s) for %s: %s",
                    len(move_attachments),
                    move.name,
                    ', '.join(move_attachments.mapped('name'))
                )
                attachments_to_delete |= move_attachments

        # Delete the cached PDFs
        if attachments_to_delete:
            attachments_to_delete.unlink()

    def _xtd_get_expected_pdf_names(self, move):
        """
        Generate list of possible PDF names that could be system-generated.

        :param move: account.move record
        :return: list of possible PDF attachment names
        """
        possible_names = []

        # Standard invoice name + .pdf
        if move.name and move.name != '/':
            # Replace slashes with safe characters (Odoo may do this in attachment names)
            safe_name = move.name.replace('/', '_')
            possible_names.append(f"{move.name}.pdf")
            possible_names.append(f"{safe_name}.pdf")

        # Report-based names (Odoo uses various patterns)
        # Pattern: "Invoice - {name}.pdf" or "Bill - {name}.pdf"
        if move.name and move.name != '/':
            if move.move_type in ('out_invoice', 'out_refund'):
                possible_names.append(f"Invoice - {move.name}.pdf")
                possible_names.append(f"Invoice-{move.name}.pdf")
            elif move.move_type in ('in_invoice', 'in_refund'):
                possible_names.append(f"Bill - {move.name}.pdf")
                possible_names.append(f"Bill-{move.name}.pdf")

        # Some localization modules may use different patterns
        # Add the reference if it exists
        if move.ref:
            possible_names.append(f"{move.ref}.pdf")

        return possible_names
