{
    'name': 'LCH Administrator',
    'summary': """Administration settings for La Casa del Hostelero""",
    'version': '12.0.1.0.0', 
    'description': """Administration settings for La Casa del Hostelero""",
    'author': 'DDL',
    'company': 'Xtendoo',
    'website': 'http://www.xtendoo.com',
    'category': 'Extra Tools',
    'depends': [
        'base',
        'sale',
        'product',
        'sale_margin',
        'product',
        'account',
    ],
    'license': 'AGPL-3',
    'data': [
        #'views/view_users_form_create_invoice.xml',
        'views/sale_order_view_restrict.xml',
        #'views/account_payment.xml',
        #'views/account_invoice_restrict.xml',
        'views/product_template_restrict.xml',
        'security/security.xml',
    ],
    'installable': True,
    'auto_install': True,
}
