{
    "name": "Multi-Compañía Obligatorio",
    "summary": "Fuerza company_id en la creación de registros y audita modelos.",
    "description": "Modulo tecnico.",
    "author": "Abraham (Xtendoo)",
    "category": "Technical",
    "version": "19.0.1.2.2",
    "depends": [
        "base",
        "product",
        "contacts",
        "stock",
        "point_of_sale",
        "sale",
        "account",
    ],
    "installable": True,
    "application": False,
    "post_init_hook": "post_init_check_company_id",
    "license": "LGPL-3",
    "data": [
        "security/product_category_rule.xml",
        "security/product_attribute_rules.xml",
        "security/product_tag_rule.xml",
        "security/partner_rules.xml",
        "security/res_partner_bank.xml",
        "security/pos_category_rule.xml",
        "security/pos_note_rule.xml",
        "views/inherit_sale_account_product_context.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "xtendoo_encapsulate_companies/static/src/js/relational_utils_company_patch.js",
        ],
    },
}
